apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
      inbound:
        rules:
        {{#each azure_access_inbound}}
            - application: {{this.application}}
              namespace: {{this.namespace}}
              cluster: {{this.cluster}}
        {{/each}}
      outbound:
        external:
        {{#each outbound-access-hosts}}
            - host: {{this}}
        {{/each}}
        rules:
        {{#each outbound-access-apps}}
            - application: {{this}}
        {{/each}}
  secureLogs:
    enabled: true
  kafka:
    pool: {{ kafka.pool }}
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 60
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /actuator/prometheus
  resources:
    limits:
      memory: {{limits.memory}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
  replicas:
    disableAutoScaling: true
    max: {{replicas.max}}
    min: {{replicas.min}}
  envFrom:
    - secret: {{unleash.secret_name}}
  gcp:
    sqlInstances:
      - name: {{ database.navn }}
        type: POSTGRES_17
        diskSize: {{ database.size }}
        tier: {{ database.tier }}
        databases:
          - name: bidrag-automatisk-jobb
            envVarPrefix: DB
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "{{ database.auditlog }}"
          - name: "pgaudit.log"
            value: "write"
          - name: "pgaudit.log_parameter"
            value: "on"
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}

