name: bidrag-automatisk-jobb
ingresses:
  - https://bidrag-automatisk-jobb.intern.nav.no
limits:
  memory: 4048Mi
requests:
  cpu: 400m
  memory: 2000Mi
replicas:
  max: 2
  min: 1
database:
  navn: bidrag-automatisk-jobb-prod
  tier: db-custom-1-3840
  size: 25
  auditlog: "on"
kafka:
  pool: nav-prod
env:
  PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_BELOPSHISTORIKK_URL: http://bidrag-belopshistorikk
  BIDRAG_BELOPSHISTORIKK_SCOPE: prod-gcp.bidrag.bidrag-belopshistorikk
  BIDRAG_VEDTAK_URL: http://bidrag-vedtak
  BIDRAG_VEDTAK_SCOPE: prod-gcp.bidrag.bidrag-vedtak
  BIDRAG_SAMHANDLER_URL: http://bidrag-samhandler
  BIDRAG_RESKONTRO_URL: https://bidrag-reskontro.intern.nav.no/
  BIDRAG_RESKONTRO_SCOPE: prod-gcp.bidrag.bidrag-reskontro
  BIDRAG_SAMHANDLER_SCOPE: prod-gcp.bidrag.bidrag-samhandler
  BIDRAG_DOKUMENT_FORSENDELSE_URL: http://bidrag-dokument-forsendelse
  BIDRAG_DOKUMENT_FORSENDELSE_SCOPE: prod-gcp.bidrag.bidrag-dokument-forsendelse
  BIDRAG_SAK_URL: https://bidrag-sak.prod-fss-pub.nais.io
  BIDRAG_SAK_SCOPE: prod-fss.bidrag.bidrag-sak
  BIDRAG_BEHANDLING_URL: https://bidrag-behandling.intern.nav.no
  BIDRAG_BEHANDLING_SCOPE: prod-gcp.bidrag.bidrag-behandling
  BIDRAG_GRUNNLAG_URL: https://bidrag-grunnlag.intern.nav.no
  BIDRAG_GRUNNLAG_SCOPE: prod-gcp.bidrag.bidrag-grunnlag
  OPPGAVE_URL: https://oppgave.prod-fss-pub.nais.io
  OPPGAVE_SCOPE: prod-fss.oppgavehandtering.oppgave
  KODEVERK_URL: http://bidrag-kodeverk
  BIDRAG_SJABLON_URL: https://bidrag-sjablon.prod-fss-pub.nais.io/bidrag-sjablon
  BIDRAG_ORGANISASJON_SCOPE: prod-fss.bidrag.bidrag-organisasjon
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.prod-fss-pub.nais.io/bidrag-organisasjon
  KAFKA_VEDTAK_TOPIC: bidrag.vedtak
  KAFKA_PERSON_HENDELSE_TOPIC: bidrag.personhendelse.v1
  VEDTAK_KAFKA_GROUP_ID_SISTE: bidrag-automatisk-jobb-siste
  VEDTAK_KAFKA_GROUP_ID_START: bidrag-automatisk-jobb-start-6
  PERSON_HENDELSE_KAFKA_GROUP_ID: bidrag-automatisk-jobb
  JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
outbound-access-apps:
  - bidrag-belopshistorikk
  - bidrag-vedtak
  - bidrag-kodeverk
  - bidrag-samhandler
  - bidrag-dokument-forsendelse
  - bidrag-reskontro
  - bidrag-behandling
  - bidrag-grunnlag
outbound-access-hosts:
  - bidrag-person.prod-fss-pub.nais.io
  - bidrag-sak.prod-fss-pub.nais.io
  - bidrag-sjablon.prod-fss-pub.nais.io
  - oppgave.prod-fss-pub.nais.io
  - bidrag-unleash-api.nav.cloud.nais.io
azure_access_inbound:
  - application: bisys
    namespace: bidrag
    cluster: prod-fss
unleash:
  env: production
  secret_name: bidrag-automatisk-jobb-unleash-api-token