name: bidrag-automatisk-jobb
ingresses:
  - https://bidrag-automatisk-jobb.intern.nav.no
limits:
  memory: 2048Mi
requests:
  cpu: 50m
  memory: 1000Mi
replicas:
  max: 2
  min: 2
database:
  navn: bidrag-automatisk-jobb-prod
  tier: db-custom-1-3840
  size: 25
  auditlog: "on"
kafka:
  pool: nav-prod
env:
  PERSON_URL: https://bidrag-person.prod-fss-pub.nais.io/bidrag-person
  PERSON_SCOPE: prod-fss.bidrag.bidrag-person
  BIDRAG_STONAD_URL: http://bidrag-stonad
  BIDRAG_STONAD_SCOPE: prod-gcp.bidrag.bidrag-stonad
  BIDRAG_VEDTAK_URL: http://bidrag-vedtak
  BIDRAG_VEDTAK_SCOPE: prod-gcp.bidrag.bidrag-vedtak
  BIDRAG_SAK_URL: https://bidrag-sak.prod-fss-pub.nais.io
  BIDRAG_SAK_SCOPE: prod-fss.bidrag.bidrag-sak
  OPPGAVE_URL: https://oppgave.prod-fss-pub.nais.io
  OPPGAVE_SCOPE: prod-fss.oppgavehandtering.oppgave
  KODEVERK_URL: http://bidrag-kodeverk
  BIDRAG_SJABLON_URL: https://bidrag-sjablon.prod-fss-pub.nais.io/bidrag-sjablon
  BIDRAG_ORGANISASJON_SCOPE: prod-fss.bidrag.bidrag-organisasjon
  BIDRAG_ORGANISASJON_URL: https://bidrag-organisasjon.prod-fss-pub.nais.io/bidrag-organisasjon
  KAFKA_VEDTAK_TOPIC: bidrag.vedtak
  KAFKA_PERSON_HENDELSE_TOPIC: bidrag.personhendelse.v1
  VEDTAK_KAFKA_GROUP_ID_SISTE: bidrag-automatisk-jobb-siste
  VEDTAK_KAFKA_GROUP_ID_START: bidrag-automatisk-jobb-start-3
  PERSON_HENDELSE_KAFKA_GROUP_ID: bidrag-automatisk-jobb
  JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0
outbound-access-apps:
  - bidrag-stonad
  - bidrag-vedtak
  - bidrag-kodeverk
outbound-access-hosts:
  - bidrag-person.prod-fss-pub.nais.io
  - bidrag-sak.prod-fss-pub.nais.io
  - bidrag-sjablon.prod-fss-pub.nais.io
  - oppgave.prod-fss-pub.nais.io
  - bidrag-unleash-api.nav.cloud.nais.io
unleash:
  env: production
  secret_name: bidrag-automatisk-jobb-unleash-api-token