name: Deploy Q2
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'
  push:
    branches:
      - 'q2/**'
      - 'Q2/**'

jobs:
  build_and_deploy:
    name: "Build and deploy to Q2"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: q2.yaml

  deploy_unleash:
    runs-on: ubuntu-latest
    name: Deploy unleash
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - name: Deploy unleash to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/unleash.yaml
          VARS: .nais/q2.yaml